name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image with build-time environment variables
      - name: Build Docker image
        run: |
          docker build --pull \
            --build-arg NEXT_PUBLIC_API_URL=https://be.el.ai.hect.dev \
            -t hectorandac/craft-sentence-extractor-fe:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push hectorandac/craft-sentence-extractor-fe:latest
